---
sudo: required

services:
  - docker

before_script:
  # Install fissile
  - wget https://concourse-hpe.s3.amazonaws.com/fissile-2.0.2%2B71.g608c02c.develop-linux.amd64.tgz -O /tmp/fissile.tgz
  - mkdir -p /tmp/fissile
  - tar -xvf /tmp/fissile.tgz -C /tmp/fissile
  - export PATH=$PATH:/tmp/fissile

script:
  - source .fissilerc
  - make
